### ISSUE TITLE
How to parallel

### ISSUE THREAD

**Issue by cz354** [WenjianBI/SPACox#2]
Hi,

When I use SPACox.plink, I don't know how to use parallel computing on different chunks. Could you give me some hits?

Thank you

**Comment by WenjianBI** [comment]
Hi,

I suggest you check the source code in SPACox::SPACox.plink. Basically, I simply use seqminer::readPlinkToMatrixByIndex function to read in genotype data and then call SPACox::SPACox. You can borrow the codes and select genotype region by yourself for parallel computation. If you still cannot handle it, please let me know. I can update it a little bit so that users can specify the region.

Thanks,
Wenjian

**Comment by cz354** [comment]
Hi,

Thank you. I followed your advise and have solved the problem.

Best,
Chi
